language: scala

scala:
  - 2.11.2

before_install:
  - sudo apt-get install build-essential
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test  
  - sudo apt-get update
  - sudo apt-get install g++-4.9
  - sudo apt-get install libtbb-dev
  - sudo apt-get install libgtest-dev
  - sudo apt-get install clang-format-3.4
  - sudo apt-get install libjemalloc-dev
  - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"

script: "sudo source ./tests/testAll.sh"

notifications:
  email:
    - craberger@gmail.com

branches:
  only:
    - master