sudo: required
services:
  - docker
before_install:
  - docker build -t $DOCKER_REPO:$COMMIT . 
script:
  - docker run $DOCKER_REPO /bin/bash -c "./test/testAll.sh"
after_success:
  - docker tag $DOCKER_REPO:$COMMIT $DOCKER_REPO:$TAG
  - docker push $DOCKER_REPO
  - echo $TAG
after_failure:
  - docker tag $DOCKER_REPO:$COMMIT $DOCKER_REPO:$COMMIT
  - docker push $DOCKER_REPO
  - echo $COMMIT
notifications:
  email:
  - craberger@gmail.com
branches:
  only:
  - eh-2.0
env:
  global:
  - secure: IyC7NnQ7Cu57et3l8CDaQK3JBWsgEnIY84c4ECfBnXnadaDEiRcicHSI8E7IVhOq8WTGVme4ig9rJx07i5JWPPfsAxzftbyEXwub9EoQvEFgJUZg+9vCgrytq6wmH/jqvtF4UC6s6ULSE/nmQbKDBCHgkCUzCoQIKGgk7NKn8ovhRBDRG0izg/COdUS6vaL5JbdCvBoLw0Q12TjuFgykLUeMQKUQZLDDY/YU653mOgjm4h82RzZlGX7YBYLFi8rkNfLa9nP7yacmnaVhxE5wKcjDcvojHFv9NNH+IXiKlEgC3A35vskLugHzMFPYL/+y12v2cyHxzyvgn4DGasgzdnuOEI/4hkMJKIYS/sAtB418Pw3TvNZjXYDFo1hxiNitOtqnNIv/wMqS2iCtQxjyRf611dCaEzsAFyXUFfOGHPcXtGlH2+hsayPmDQ6TDWz3x3hmK57fI73ytlD1K2Fe1uoLq+2QtCE7RyPJm20BmMbVFICeUr+kLc8AWl0U47AD3QUOIhRAvkUi9TlLGSqq4k1V4+kmZ0doCAxI8zmP9KjVnAh2apfOZNy4EcOGUJ0oubBgUaQmhEgjpPtNOKTEeVR2cjH/OxiMEVRpDOEjTpE1gwkzTW9mWsYM8YZW+IbAwGgofznzrFaTQjpBlWpm14IYwUEpLKoSZcyFIgC8Phw=
  - secure: iG2m4CvaDp9nPuJ21orm0uSFNkm4Aa2RD9dHpeajn7d7ivrcAiDUv8dwW4VZHiUyAXQXpvfNYOlJYD4t6RpuD2K65CxzYq4lAyxmi24PR3+N4a6xXt5tL1LSdTFShpCl30oO0k4rbXsi7Cf0sE3IAeB9jDaoMYLewcfUz/2WLuJ+KR6jJ+W7Qo8BZDwmSJKCU3vheR3lLpXdu5y8rXn/15/Tk6nTaEJ6dXQ7FmorD+Y0M8jh1AGzU40eOB5McVAk1x4HAt4WeIYFJjgAhN+aPeDRm3OcSbrJFLZe5fAPDDp3WFHYDf+vIpWIozN5uOAbfXB6mo3/XDm0uRQd2eSrB3Vocg589H5qs1QVef6CPylwswWbSSVEccHVk1RZVd/bmpdt90P9xJz/0cEBXhxlOnMaR6iNIDRB8oqQ5eRpeVMwy++RrpCj1D4kX+TKEjuKQB0PEPvNFFehUvP7NoWA1lP9a7CPhDciPclALCHCXccgO6UCbOuUhKNSphMO4+OspacVD+Qf+i+jGZwrmHI0p9DKeHHMZGNR3ffdAcI6MdO9N5IznbichWREKMgCDPk7iFeBF4mzOLSCY3mQyiY1jMgy0dNeRvkfQSZdTTxsckyk/8zPJaaI8KnIX3PuK89qLU9cfiusL5aCQuyhfjBHlY4/qnzOAOhANvb09ib1+bY=
  - secure: SPpZKUwK7f5Lq7VR+iZwyCneFL9ZuIApQW26NC213rYgOST5Hxl1bYlDTC4anvTtqh/oAR3V44iyWK/5kwDhF+SBhnkAECFyV2u2gz4/hLcaEoAOBt34mMKKrIOJrLTVf4DryzF682dc5r02TWiS7kadmqvou/lXus/TtytLqPmnNHmTpO638XA6azgwLvVEi4bmpGxcy9xvGIP78Cu1bhU/C4vjE+zfTjSWw/4iXXfOtXeM5dJT3zC66VNCPABrpm8Mi5PnTbY78Qwuu06wjpLnKk6vI6lMnMLHtiTvEA/cPRT4MFFsgA5zTal021ywhrIwIhQXNLBwlroGbha0EGRLFtYfKosWLWMxRteYEBDTQaxfZRB2TRNX1udAWVXZEhrMbDwUynMYHsBEIu0LUnFhrR0H38dv1ETaYAZpTK80XIet7A6UpyEU+n6yzpWVo8ToxlsmkfHqH7fOD+FM8ld7+Jv4S+HOIobT+/YVYdPiSi0ETHCPwBUdAvR6OuflZOB6Qiqw/ci3qIs+GVk/CAl1ov6+jff22GyTuhDNLlXwqdzmZ94YMWHVlfL9MMCZ4QNLx4jApgTJL4MtancNqXK3Yfa5YsmIg+c/AdVFJetYRseT/8KJy3N3GtOpsouHzkzRy1R8Z6ZYwfh6Dnx+VDKXYzHnrcdCoK2PaVamFTs=
  - DOCKER_REPO=craberger/emptyheaded
  - COMMIT=${TRAVIS_COMMIT::8}
  - TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`